#############################################################################
# Makefile for building: qmloscilloscope
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  qmloscilloscope.pro
# Template: app
# Command: /home/linux/raspi/qt5/bin/qmake -o Makefile qmloscilloscope.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/linux/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/linux/raspi/sysroot -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../raspi/qt5pi/include -I../raspi/qt5pi/include/QtCharts -I../raspi/qt5pi/include/QtWidgets -I../raspi/qt5pi/include/QtQuick -I../raspi/qt5pi/include/QtGui -I../raspi/qt5pi/include/QtQml -I../raspi/qt5pi/include/QtNetwork -I../raspi/qt5pi/include/QtSerialPort -I../raspi/qt5pi/include/QtCore -I. -I=/opt/vc/include -I=/opt/vc/include/interface/vcos/pthreads -I=/opt/vc/include/interface/vmcs_host/linux -I../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++
QMAKE         = /home/linux/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/linux/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/linux/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qmloscilloscope1.0.0
DISTDIR = /home/linux/ventilator/.tmp/qmloscilloscope1.0.0
LINK          = /home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/linux/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/linux/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/linux/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/linux/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) -L=/opt/vc/lib /home/linux/raspi/qt5pi/lib/libQt5Charts.so /home/linux/raspi/qt5pi/lib/libQt5Widgets.so /home/linux/raspi/qt5pi/lib/libQt5Quick.so /home/linux/raspi/qt5pi/lib/libQt5Gui.so /home/linux/raspi/qt5pi/lib/libQt5Qml.so /home/linux/raspi/qt5pi/lib/libQt5Network.so /home/linux/raspi/qt5pi/lib/libQt5SerialPort.so /home/linux/raspi/qt5pi/lib/libQt5Core.so /home/linux/raspi/sysroot/usr/lib/arm-linux-gnueabihf/libGLESv2.so -lpthread   
AR            = /home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_resources.cpp \
		moc_datasource.cpp \
		moc_messageboard.cpp
OBJECTS       = main.o \
		qrc_resources.o \
		moc_datasource.o \
		moc_messageboard.o
DIST          = qml/qmloscilloscope/* \
		../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/toolchain.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/qmake_use.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		qmloscilloscope.pro datasource.h \
		messageboard.h main.cpp
QMAKE_TARGET  = qmloscilloscope
DESTDIR       = 
TARGET        = qmloscilloscope


first: all
####### Build rules

qmloscilloscope:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qmloscilloscope.pro ../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf ../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quick.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/toolchain.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/qmake_use.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		qmloscilloscope.pro \
		resources.qrc
	$(QMAKE) -o Makefile qmloscilloscope.pro
../raspi/qt5/mkspecs/features/spec_pre.prf:
../raspi/qt5/mkspecs/common/unix.conf:
../raspi/qt5/mkspecs/common/linux.conf:
../raspi/qt5/mkspecs/common/sanitize.conf:
../raspi/qt5/mkspecs/common/gcc-base.conf:
../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../raspi/qt5/mkspecs/common/g++-base.conf:
../raspi/qt5/mkspecs/common/g++-unix.conf:
../raspi/qt5/mkspecs/qdevice.pri:
../raspi/qt5/mkspecs/features/device_config.prf:
../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../raspi/qt5/mkspecs/qconfig.pri:
../raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_charts.pri:
../raspi/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qml.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../raspi/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quick.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../raspi/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
../raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../raspi/qt5/mkspecs/features/qt_functions.prf:
../raspi/qt5/mkspecs/features/qt_config.prf:
../raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++/qmake.conf:
../raspi/qt5/mkspecs/features/spec_post.prf:
../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../raspi/qt5/mkspecs/features/toolchain.prf:
../raspi/qt5/mkspecs/features/default_pre.prf:
../raspi/qt5/mkspecs/features/resolve_config.prf:
../raspi/qt5/mkspecs/features/default_post.prf:
../raspi/qt5/mkspecs/features/warn_on.prf:
../raspi/qt5/mkspecs/features/qt.prf:
../raspi/qt5/mkspecs/features/resources.prf:
../raspi/qt5/mkspecs/features/moc.prf:
../raspi/qt5/mkspecs/features/unix/opengl.prf:
../raspi/qt5/mkspecs/features/uic.prf:
../raspi/qt5/mkspecs/features/unix/thread.prf:
../raspi/qt5/mkspecs/features/qmake_use.prf:
../raspi/qt5/mkspecs/features/file_copies.prf:
../raspi/qt5/mkspecs/features/testcase_targets.prf:
../raspi/qt5/mkspecs/features/exceptions.prf:
../raspi/qt5/mkspecs/features/yacc.prf:
../raspi/qt5/mkspecs/features/lex.prf:
qmloscilloscope.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile qmloscilloscope.pro

qmake_all: FORCE


all: Makefile qmloscilloscope

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents datasource.h messageboard.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../raspi/qt5/bin/rcc \
		qml/qmloscilloscope/Settings.qml \
		qml/qmloscilloscope/ControlPanel.qml \
		qml/qmloscilloscope/MultiButton.qml \
		qml/qmloscilloscope/Charts.qml \
		qml/qmloscilloscope/main.qml \
		qml/qmloscilloscope/ScopeView.qml
	/home/linux/raspi/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../raspi/qt5/mkspecs/features/data/dummy.cpp
	/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++ -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/linux/raspi/sysroot -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_datasource.cpp moc_messageboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_datasource.cpp moc_messageboard.cpp
moc_datasource.cpp: datasource.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCharts/QXYSeries \
		../raspi/qt5pi/include/QtCharts/qxyseries.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCharts/QAreaSeries \
		../raspi/qt5pi/include/QtCharts/qareaseries.h \
		../raspi/qt5pi/include/QtQuick/QQuickView \
		../raspi/qt5pi/include/QtQuick/qquickview.h \
		../raspi/qt5pi/include/QtQuick/qquickwindow.h \
		../raspi/qt5pi/include/QtQuick/qtquickglobal.h \
		../raspi/qt5pi/include/QtQml/qtqmlglobal.h \
		../raspi/qt5pi/include/QtQml/qtqml-config.h \
		../raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		../raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		../raspi/qt5pi/include/QtQuick/qtquick-config.h \
		../raspi/qt5pi/include/QtQuick/qsgrendererinterface.h \
		../raspi/qt5pi/include/QtQuick/qsgnode.h \
		../raspi/qt5pi/include/QtQuick/qsggeometry.h \
		../raspi/qt5pi/include/QtGui/qopengl.h \
		../raspi/qt5pi/include/QtCore/qt_windows.h \
		../raspi/qt5pi/include/QtGui/qopengles2ext.h \
		../raspi/qt5pi/include/QtGui/qopenglext.h \
		../raspi/qt5pi/include/QtCore/QRectF \
		../raspi/qt5pi/include/QtGui/QMatrix4x4 \
		../raspi/qt5pi/include/QtGui/qmatrix4x4.h \
		../raspi/qt5pi/include/QtGui/qvector3d.h \
		../raspi/qt5pi/include/QtGui/qvector4d.h \
		../raspi/qt5pi/include/QtGui/qquaternion.h \
		../raspi/qt5pi/include/QtGui/qgenericmatrix.h \
		../raspi/qt5pi/include/QtGui/qwindow.h \
		../raspi/qt5pi/include/QtCore/QEvent \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtCore/QRect \
		../raspi/qt5pi/include/QtGui/qsurface.h \
		../raspi/qt5pi/include/QtGui/qsurfaceformat.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtQml/qqml.h \
		../raspi/qt5pi/include/QtQml/qqmlprivate.h \
		../raspi/qt5pi/include/QtQml/qqmlparserstatus.h \
		../raspi/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		../raspi/qt5pi/include/QtQml/qqmllist.h \
		../raspi/qt5pi/include/QtCore/qmetaobject.h \
		../raspi/qt5pi/include/QtQml/qqmldebug.h \
		../raspi/qt5pi/include/QtQuick/QQuickItem \
		../raspi/qt5pi/include/QtQuick/qquickitem.h \
		../raspi/qt5pi/include/QtQml/qqmlcomponent.h \
		../raspi/qt5pi/include/QtQml/qqmlerror.h \
		../raspi/qt5pi/include/QtQml/qjsvalue.h \
		../raspi/qt5pi/include/QtCore/QList \
		../raspi/qt5pi/include/QtGui/qaccessible.h \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtCore/QDebug \
		../raspi/qt5pi/include/QtCore/QRandomGenerator \
		../raspi/qt5pi/include/QtCore/qrandom.h \
		../raspi/qt5pi/include/QtCore/QtMath \
		../raspi/qt5pi/include/QtCore/qmath.h \
		../raspi/qt5pi/include/QtSerialPort/QSerialPort \
		../raspi/qt5pi/include/QtSerialPort/qserialport.h \
		../raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		moc_predefs.h \
		../raspi/qt5/bin/moc
	/home/linux/raspi/qt5/bin/moc $(DEFINES) --include /home/linux/ventilator/moc_predefs.h -I/home/linux/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/linux/ventilator -I/home/linux/raspi/qt5pi/include -I/home/linux/raspi/qt5pi/include/QtCharts -I/home/linux/raspi/qt5pi/include/QtWidgets -I/home/linux/raspi/qt5pi/include/QtQuick -I/home/linux/raspi/qt5pi/include/QtGui -I/home/linux/raspi/qt5pi/include/QtQml -I/home/linux/raspi/qt5pi/include/QtNetwork -I/home/linux/raspi/qt5pi/include/QtSerialPort -I/home/linux/raspi/qt5pi/include/QtCore -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/linux/raspi/sysroot/usr/include -I/home/linux/raspi/sysroot/usr/include/arm-linux-gnueabihf datasource.h -o moc_datasource.cpp

moc_messageboard.cpp: messageboard.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/QDebug \
		moc_predefs.h \
		../raspi/qt5/bin/moc
	/home/linux/raspi/qt5/bin/moc $(DEFINES) --include /home/linux/ventilator/moc_predefs.h -I/home/linux/raspi/qt5/mkspecs/devices/linux-rasp-pi3-g++ -I/home/linux/ventilator -I/home/linux/raspi/qt5pi/include -I/home/linux/raspi/qt5pi/include/QtCharts -I/home/linux/raspi/qt5pi/include/QtWidgets -I/home/linux/raspi/qt5pi/include/QtQuick -I/home/linux/raspi/qt5pi/include/QtGui -I/home/linux/raspi/qt5pi/include/QtQml -I/home/linux/raspi/qt5pi/include/QtNetwork -I/home/linux/raspi/qt5pi/include/QtSerialPort -I/home/linux/raspi/qt5pi/include/QtCore -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/linux/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/linux/raspi/sysroot/usr/include -I/home/linux/raspi/sysroot/usr/include/arm-linux-gnueabihf messageboard.h -o moc_messageboard.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../raspi/qt5pi/include/QtWidgets/QApplication \
		../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgetsglobal.h \
		../raspi/qt5pi/include/QtGui/qtguiglobal.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qtcore-config.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtGui/qtgui-config.h \
		../raspi/qt5pi/include/QtWidgets/qtwidgets-config.h \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringliteral.h \
		../raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		../raspi/qt5pi/include/QtCore/qstringview.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../raspi/qt5pi/include/QtQml/QQmlContext \
		../raspi/qt5pi/include/QtQml/qqmlcontext.h \
		../raspi/qt5pi/include/QtQml/qjsvalue.h \
		../raspi/qt5pi/include/QtQml/qtqmlglobal.h \
		../raspi/qt5pi/include/QtQml/qtqml-config.h \
		../raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		../raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		../raspi/qt5pi/include/QtQuick/QQuickView \
		../raspi/qt5pi/include/QtQuick/qquickview.h \
		../raspi/qt5pi/include/QtQuick/qquickwindow.h \
		../raspi/qt5pi/include/QtQuick/qtquickglobal.h \
		../raspi/qt5pi/include/QtQuick/qtquick-config.h \
		../raspi/qt5pi/include/QtQuick/qsgrendererinterface.h \
		../raspi/qt5pi/include/QtQuick/qsgnode.h \
		../raspi/qt5pi/include/QtQuick/qsggeometry.h \
		../raspi/qt5pi/include/QtGui/qopengl.h \
		../raspi/qt5pi/include/QtCore/qt_windows.h \
		../raspi/qt5pi/include/QtGui/qopengles2ext.h \
		../raspi/qt5pi/include/QtGui/qopenglext.h \
		../raspi/qt5pi/include/QtCore/QRectF \
		../raspi/qt5pi/include/QtGui/QMatrix4x4 \
		../raspi/qt5pi/include/QtGui/qmatrix4x4.h \
		../raspi/qt5pi/include/QtGui/qvector3d.h \
		../raspi/qt5pi/include/QtGui/qvector4d.h \
		../raspi/qt5pi/include/QtGui/qquaternion.h \
		../raspi/qt5pi/include/QtGui/qgenericmatrix.h \
		../raspi/qt5pi/include/QtGui/qwindow.h \
		../raspi/qt5pi/include/QtCore/QObject \
		../raspi/qt5pi/include/QtCore/QEvent \
		../raspi/qt5pi/include/QtCore/QMargins \
		../raspi/qt5pi/include/QtCore/QRect \
		../raspi/qt5pi/include/QtGui/qsurface.h \
		../raspi/qt5pi/include/QtGui/qsurfaceformat.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtQml/qqml.h \
		../raspi/qt5pi/include/QtQml/qqmlprivate.h \
		../raspi/qt5pi/include/QtQml/qqmlparserstatus.h \
		../raspi/qt5pi/include/QtQml/qqmlpropertyvaluesource.h \
		../raspi/qt5pi/include/QtQml/qqmllist.h \
		../raspi/qt5pi/include/QtCore/qmetaobject.h \
		../raspi/qt5pi/include/QtQml/qqmldebug.h \
		../raspi/qt5pi/include/QtQml/QQmlEngine \
		../raspi/qt5pi/include/QtQml/qqmlengine.h \
		../raspi/qt5pi/include/QtQml/qjsengine.h \
		../raspi/qt5pi/include/QtQml/qqmlerror.h \
		../raspi/qt5pi/include/QtCore/QDir \
		../raspi/qt5pi/include/QtCore/qdir.h \
		../raspi/qt5pi/include/QtCore/qfileinfo.h \
		datasource.h \
		../raspi/qt5pi/include/QtCharts/QAbstractSeries \
		../raspi/qt5pi/include/QtCharts/qabstractseries.h \
		../raspi/qt5pi/include/QtCharts/QChartGlobal \
		../raspi/qt5pi/include/QtCharts/qchartglobal.h \
		../raspi/qt5pi/include/QtCore/QtGlobal \
		../raspi/qt5pi/include/QtCharts/QAbstractAxis \
		../raspi/qt5pi/include/QtCharts/qabstractaxis.h \
		../raspi/qt5pi/include/QtGui/QPen \
		../raspi/qt5pi/include/QtGui/qpen.h \
		../raspi/qt5pi/include/QtGui/QFont \
		../raspi/qt5pi/include/QtCore/QVariant \
		../raspi/qt5pi/include/QtCharts/QXYSeries \
		../raspi/qt5pi/include/QtCharts/qxyseries.h \
		../raspi/qt5pi/include/QtGui/QBrush \
		../raspi/qt5pi/include/QtCharts/QAreaSeries \
		../raspi/qt5pi/include/QtCharts/qareaseries.h \
		../raspi/qt5pi/include/QtQuick/QQuickItem \
		../raspi/qt5pi/include/QtQuick/qquickitem.h \
		../raspi/qt5pi/include/QtQml/qqmlcomponent.h \
		../raspi/qt5pi/include/QtCore/QList \
		../raspi/qt5pi/include/QtGui/qaccessible.h \
		../raspi/qt5pi/include/QtCore/QDebug \
		../raspi/qt5pi/include/QtCore/QRandomGenerator \
		../raspi/qt5pi/include/QtCore/qrandom.h \
		../raspi/qt5pi/include/QtCore/QtMath \
		../raspi/qt5pi/include/QtCore/qmath.h \
		../raspi/qt5pi/include/QtSerialPort/QSerialPort \
		../raspi/qt5pi/include/QtSerialPort/qserialport.h \
		../raspi/qt5pi/include/QtSerialPort/qserialportglobal.h \
		messageboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_datasource.o: moc_datasource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datasource.o moc_datasource.cpp

moc_messageboard.o: moc_messageboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messageboard.o moc_messageboard.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope || mkdir -p $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/linux/raspi/qt5pi/examples/charts/qmloscilloscope/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

